spring.application.name=inshore-pos

spring.datasource.url=jdbc:postgresql://localhost:5432/InshorePosDB
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${INSHORE_JWT_SECRET}

spring.profiles.active=dev